version: '3.8'

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: blog-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./djangoBlog
      dockerfile: Dockerfile
    image: blog-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./blog_temp_data:/app/blog_temp_data
    env_file: 
      - .env
    depends_on:
      - redis
      - mysql
    restart: always
    
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: always
    
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    
volumes:
  mysql_data: 
