version: '3.8'

services:
  frontend:
    image: blog-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
 
  backend:
    image: blog-backend:latest
    ports:
      - "8000:8000"   
    volumes:
      - /Users/qiuzx/workspace/blog_doc:/app/data  ## 挂载本地目录到容器，对应修改，同时保证数据库的挂载目录一致
    environment:
      - HOST_DATA_PATH=/Users/qiuzx/workspace/blog_doc  ## 挂载本地目录到容器，对应修改，同时保证数据库的挂载目录一致
      - CONTAINER_DATA_PATH=/app/data
    depends_on:
      - redis
      - mysql
    restart: always
    
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: always
    
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    
volumes:
  mysql_data: 
