# Generated by Django 5.1.4 on 2025-04-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_key', models.CharField(max_length=255)),
                ('visible_users', models.TextField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_config_path', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'system_settin11gs',
            },
        ),
    ]
