# Generated by Django 5.1.4 on 2025-04-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systemsetting',
            table='system_settings',
        ),
    ]
